# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executor',
            options={'verbose_name': 'executor', 'verbose_name_plural': 'executores'},
        ),
    ]
