# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposolicitacao',
            options={'verbose_name': 'tipo de solicitação', 'verbose_name_plural': 'tipos de solicitação'},
        ),
    ]
