language: python
python: 
  - "3.6" 
env:
  - DEBUG=False
  - SECRET_KEY=214iiunhm0g#nze#2lyz7zn&6lc!)!ri=u6zobiy()q&$^0)&f
  - SQLITE_URL=db.sqlite3
  - STATIC_ROOT=/static/
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
      - sshpass
after_success:
  - sshpass -p ${pass_scp} ssh -o StrictHostKeyChecking=no ${user_scp}@${server_scp} "cd /home/${user_scp}/dados-camara-colombo && sh deploy.sh"