language: python
python: 
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python --version
  - ./manage.py test
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
      - sshpass
after_success:
  - sshpass -p ${pass_scp} ssh -o StrictHostKeyChecking=no ${user_scp}@${server_scp} "cd /home/${user_scp}/dados-camara-colombo && sh deploy.sh"