language: python
python: 
  - "3.7"
cache:
  - pip
services:
  - mysql
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
before_script:
  - cp .env.example .env
  - mysql -e 'create database test' -u root
script:
  - python --version
  - python manage.py test --no-input
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
      - sshpass
after_success:
  - sshpass -p ${pass_scp} ssh -o StrictHostKeyChecking=no ${user_scp}@${server_scp} "cd /home/${user_scp}/dados-camara-colombo && sh deploy.sh"
