language: python
python: 
  - "3.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
# before_script:
#   - python manage.py migrate --no-input
script:
  - python --version
  #- python manage.py test
notifications:
  email:
    recipients:
      - mayron.ceccon@gmail.com
    on_success: always
    on_failure: always
addons:
  apt:
    packages:
      - sshpass
after_success:
  - sshpass -p ${pass_scp} ssh -o StrictHostKeyChecking=no ${user_scp}@${server_scp} "cd /home/${user_scp}/dados-camara-colombo && sh deploy.sh"
