# Generated by Django 2.0.8 on 2018-12-12 19:18

from django.db import migrations, models
import vereador_link.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vereador', '0004_auto_20181124_1414'),
        ('tipo_solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VereadorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('ano', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=vereador_link.models.current_year, null=True)),
                ('tipo', models.ManyToManyField(to='tipo_solicitacao.TipoSolicitacao')),
                ('vereador', models.ManyToManyField(to='vereador.Vereador')),
            ],
        ),
    ]
