# Generated by Django 2.0.8 on 2018-12-12 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0004_auto_20181124_1414'),
        ('tipo_solicitacao', '0001_initial'),
        ('vereador_link', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vereadorlink',
            name='tipo',
        ),
        migrations.AddField(
            model_name='vereadorlink',
            name='tipo',
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_solicitacao.TipoSolicitacao'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vereadorlink',
            name='vereador',
        ),
        migrations.AddField(
            model_name='vereadorlink',
            name='vereador',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='vereador.Vereador'),
            preserve_default=False,
        ),
    ]
