# Generated by Django 2.0.8 on 2018-12-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vereador_link', '0004_auto_20181212_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vereadorlink',
            name='vereador',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='links', to='vereador.Vereador'),
        ),
    ]
