# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vereador_link', '0006_auto_20190219_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vereadorlink',
            options={'verbose_name': 'link de vereador', 'verbose_name_plural': 'links de vereadores'},
        ),
    ]
