# Generated by Django 2.0.8 on 2018-12-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_lei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='vereador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vereador.Vereador'),
        ),
    ]
