# Generated by Django 2.0.8 on 2018-12-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_lei', '0002_auto_20181212_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='vereador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='projetos', to='vereador.Vereador'),
        ),
    ]
