# Generated by Django 2.0.8 on 2019-02-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_lei', '0004_auto_20181212_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetolei',
            name='protocolo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
