# Generated by Django 2.0.8 on 2019-02-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_lei', '0005_auto_20190219_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetolei',
            name='protocolo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
