# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_lei', '0006_auto_20190219_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetolei',
            options={'verbose_name': 'projeto de lei', 'verbose_name_plural': 'projetos de lei'},
        ),
    ]
