# Generated by Django 2.0.8 on 2018-11-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vereador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
