# Generated by Django 2.0.8 on 2018-12-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0004_auto_20181124_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
