# Generated by Django 2.0.8 on 2018-12-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0007_auto_20181215_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vereador',
            old_name='anos',
            new_name='legislaturas',
        ),
    ]
