# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0011_auto_20190531_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vereador',
            options={'verbose_name': 'vereador', 'verbose_name_plural': 'vereadores'},
        ),
    ]
