# Generated by Django 2.0.7 on 2018-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('link', models.TextField(max_length=255)),
                ('cadastro', models.DateField(auto_now=True)),
            ],
        ),
    ]
