# Generated by Django 2.0.7 on 2018-11-13 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='data_sessao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pauta',
            name='descricao',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
