# Generated by Django 2.0.7 on 2018-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0002_auto_20181113_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
