# Generated by Django 2.0.7 on 2018-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0003_auto_20181113_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
