# Generated by Django 2.0.8 on 2018-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0005_auto_20181115_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
