# Generated by Django 2.2 on 2019-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0007_pauta_indicacao_exportada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
