# Generated by Django 2.2.5 on 2019-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0008_auto_20190531_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
