# Generated by Django 2.2.5 on 2019-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0009_auto_20191201_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
