# Generated by Django 2.2.5 on 2019-12-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0010_auto_20191201_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='link',
            field=models.URLField(),
        ),
    ]
