# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pauta', '0014_auto_20191201_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pauta',
            options={'verbose_name': 'pauta', 'verbose_name_plural': 'pautas'},
        ),
    ]
