# Generated by Django 2.2 on 2019-04-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pauta', '0006_auto_20181216_1226'),
        ('vereador', '0010_auto_20190219_2029'),
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                   related_name='indicacoes', to='executor.Executor')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            related_name='indicacoes', to='pauta.Pauta')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               related_name='indicacoes', to='vereador.Vereador')),
            ],
        ),
    ]
