# Generated by Django 3.0 on 2019-12-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacao', '0003_auto_20190428_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacao',
            options={'verbose_name': 'indicação', 'verbose_name_plural': 'indicações'},
        ),
    ]
